image: node
cache:
  paths:
    - node_modules/
build:
  stage: build
  script:
    - npm install
    - npm run build -- --prod
  artifacts:
    expire_in: 1 week
    paths:
      - dist/
deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - npx ipfs-deploy -p pinata -d cloudflare -C -O
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
