image: node
cache:
  paths:
    - node_modules/
before_script:
  - npm install
build:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: none
  script:
    - npx ipfs-deploy -p pinata -d cloudflare
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
