on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
      - run: npm ci
      - run: npm run build --if-present -- --base-href .
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist/tso-tools/browser
      - run: npm test -- --no-watch --no-progress --browsers=ChromeHeadless --code-coverage --reporters junit
      - uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: TESTS-*.xml
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
  dependabot:
    if: github.event.pull_request.user.login == 'dependabot[bot]'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
