on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test -- --no-watch --no-progress --browsers=ChromeHeadless --code-coverage --reporters junit
      - uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: TESTS-*.xml

